extern NSString* const INFOPLIST_KEY_ADMOB_BANNER_ID;
extern NSString* const INFOPLIST_KEY_ADMOB_INTERSTITIAL_ID;
extern NSString* const INFOPLIST_KEY_ADMOB_REWARDED_ID;
extern NSString* const INFOPLIST_KEY_ADMOB_NATIVE_ADVANCED_ID;
